{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozhimen.study.plugin",
    "module": "first_plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "first_plugin-1.0.0.jar",
          "url": "first_plugin-1.0.0.jar",
          "size": 2343,
          "sha512": "d06f0f20dca04c74423a3fa6904698c352214ea75d40097f1f4b3ffe0de7d7d6b83b7b08f0bbbe24e1cb7211a9a5979503fce0f3856d6995b4265662bc9f0ef4",
          "sha256": "4d5714902ec9a39fc51013f4474111f1abe4f53e6673aa77b1be5f02af06480a",
          "sha1": "edbdc4ed85a9b7b67aea56ca71a0e450aa7b7f15",
          "md5": "d2f11e20b44b0c1d62428d613a4d0ee4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "first_plugin-1.0.0.jar",
          "url": "first_plugin-1.0.0.jar",
          "size": 2343,
          "sha512": "d06f0f20dca04c74423a3fa6904698c352214ea75d40097f1f4b3ffe0de7d7d6b83b7b08f0bbbe24e1cb7211a9a5979503fce0f3856d6995b4265662bc9f0ef4",
          "sha256": "4d5714902ec9a39fc51013f4474111f1abe4f53e6673aa77b1be5f02af06480a",
          "sha1": "edbdc4ed85a9b7b67aea56ca71a0e450aa7b7f15",
          "md5": "d2f11e20b44b0c1d62428d613a4d0ee4"
        }
      ]
    }
  ]
}
